# Generated by Django 3.2.8 on 2022-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Completed'), (2, 'In progress'), (3, 'Not started')], default=3)),
                ('rank', models.IntegerField(choices=[(None, 'Выберите насколько важна задача'), (1, 'Important'), (2, 'Average'), (3, 'Small')])),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
